/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.adfab.magebeans.guis;

import fr.adfab.magebeans.processes.CreateModuleProcess;
import java.io.FileNotFoundException;
import org.openide.util.Exceptions;

/**
 *
 * @author vanguyen
 */
public class CreateModuleForm extends javax.swing.JDialog {

    protected String projectDir;

    public void setProjectDir(String projectDir) {
        this.projectDir = projectDir;
    }
    
    /**
     * Creates new form CreateModuleForm
     */
    public CreateModuleForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboxBlock = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        cboxModel = new javax.swing.JCheckBox();
        cboxHelper = new javax.swing.JCheckBox();
        cboxResourceModel = new javax.swing.JCheckBox();
        btnCreate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rbtnCommunity = new javax.swing.JRadioButton();
        rbtnLocal = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtCompany = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtModule = new javax.swing.JTextField();
        cboxSetup = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        org.openide.awt.Mnemonics.setLocalizedText(cboxBlock, org.openide.util.NbBundle.getMessage(CreateModuleForm.class, "CreateModuleForm.cboxBlock.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(CreateModuleForm.class, "CreateModuleForm.jLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(cboxModel, org.openide.util.NbBundle.getMessage(CreateModuleForm.class, "CreateModuleForm.cboxModel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(cboxHelper, org.openide.util.NbBundle.getMessage(CreateModuleForm.class, "CreateModuleForm.cboxHelper.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(cboxResourceModel, org.openide.util.NbBundle.getMessage(CreateModuleForm.class, "CreateModuleForm.cboxResourceModel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnCreate, org.openide.util.NbBundle.getMessage(CreateModuleForm.class, "CreateModuleForm.btnCreate.text")); // NOI18N
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btnCancel, org.openide.util.NbBundle.getMessage(CreateModuleForm.class, "CreateModuleForm.btnCancel.text")); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(CreateModuleForm.class, "CreateModuleForm.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(rbtnCommunity, org.openide.util.NbBundle.getMessage(CreateModuleForm.class, "CreateModuleForm.rbtnCommunity.text")); // NOI18N

        rbtnLocal.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(rbtnLocal, org.openide.util.NbBundle.getMessage(CreateModuleForm.class, "CreateModuleForm.rbtnLocal.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(CreateModuleForm.class, "CreateModuleForm.jLabel2.text")); // NOI18N

        txtCompany.setText(org.openide.util.NbBundle.getMessage(CreateModuleForm.class, "CreateModuleForm.txtCompany.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(CreateModuleForm.class, "CreateModuleForm.jLabel3.text")); // NOI18N

        txtModule.setText(org.openide.util.NbBundle.getMessage(CreateModuleForm.class, "CreateModuleForm.txtModule.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(cboxSetup, org.openide.util.NbBundle.getMessage(CreateModuleForm.class, "CreateModuleForm.cboxSetup.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboxBlock)
                        .addGap(18, 18, 18)
                        .addComponent(cboxModel)
                        .addGap(18, 18, 18)
                        .addComponent(cboxHelper))
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboxResourceModel)
                        .addGap(18, 18, 18)
                        .addComponent(cboxSetup))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnCreate)
                            .addGap(18, 18, 18)
                            .addComponent(btnCancel))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rbtnCommunity)
                                    .addGap(35, 35, 35)
                                    .addComponent(rbtnLocal))
                                .addComponent(txtCompany)
                                .addComponent(txtModule, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rbtnCommunity)
                    .addComponent(rbtnLocal))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtModule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxBlock)
                    .addComponent(cboxModel)
                    .addComponent(cboxHelper))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxSetup)
                    .addComponent(cboxResourceModel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnCancel))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        CreateModuleProcess createModuleProcess = new CreateModuleProcess();

        String codePool = "local";
        if (rbtnCommunity.isSelected()) {
            codePool = "community";
        }

        try {
            createModuleProcess.setProjectDir(this.projectDir);
            createModuleProcess.setCodePool(codePool);
            createModuleProcess.setCompany(txtCompany.getText());
            createModuleProcess.setModule(txtModule.getText());

            if (cboxBlock.isSelected()) {
                createModuleProcess.setHasBlock(true);
            }

            if (cboxModel.isSelected()) {
                createModuleProcess.setHasModel(true);
            }

            if (cboxHelper.isSelected()) {
                createModuleProcess.setHasHelper(true);
            }

            if (cboxSetup.isSelected()) {
                createModuleProcess.setHasSetup(true);
            }

            createModuleProcess.process();
            dispose();
        } catch (FileNotFoundException | IllegalArgumentException ex) {
            Exceptions.printStackTrace(ex);
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(final String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateModuleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                CreateModuleForm dialog = new CreateModuleForm(new javax.swing.JFrame(), true);
                dialog.setProjectDir(args[0]);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreate;
    private javax.swing.JCheckBox cboxBlock;
    private javax.swing.JCheckBox cboxHelper;
    private javax.swing.JCheckBox cboxModel;
    private javax.swing.JCheckBox cboxResourceModel;
    private javax.swing.JCheckBox cboxSetup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rbtnCommunity;
    private javax.swing.JRadioButton rbtnLocal;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtModule;
    // End of variables declaration//GEN-END:variables
}
